# Generated by Django 4.2.7 on 2023-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_task_taskdesc_remove_task_tasktitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskDesc',
            field=models.TextField(default='Your default value here'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(default='Your default title here', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
